[2022-11-22T01:15:13.991+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: PG_to_S3.PG_to_S3 manual__2022-11-21T21:26:12.692587+00:00 [queued]>
[2022-11-22T01:15:14.021+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: PG_to_S3.PG_to_S3 manual__2022-11-21T21:26:12.692587+00:00 [queued]>
[2022-11-22T01:15:14.030+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T01:15:14.034+0000] {taskinstance.py:1363} INFO - Starting attempt 70 of 70
[2022-11-22T01:15:14.040+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T01:15:14.065+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresToS3Operator): PG_to_S3> on 2022-11-21 21:26:12.692587+00:00
[2022-11-22T01:15:14.080+0000] {standard_task_runner.py:55} INFO - Started process 28605 to run task
[2022-11-22T01:15:14.089+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'PG_to_S3', 'PG_to_S3', 'manual__2022-11-21T21:26:12.692587+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/PGtoS3.py', '--cfg-path', '/tmp/tmpyp53c6ft']
[2022-11-22T01:15:14.107+0000] {standard_task_runner.py:83} INFO - Job 184: Subtask PG_to_S3
[2022-11-22T01:15:14.270+0000] {task_command.py:376} INFO - Running <TaskInstance: PG_to_S3.PG_to_S3 manual__2022-11-21T21:26:12.692587+00:00 [running]> on host b785e9657fa7
[2022-11-22T01:15:14.383+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=eugeny
AIRFLOW_CTX_DAG_ID=PG_to_S3
AIRFLOW_CTX_TASK_ID=PG_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T21:26:12.692587+00:00
AIRFLOW_CTX_TRY_NUMBER=70
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-21T21:26:12.692587+00:00
[2022-11-22T01:15:15.943+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/pgtos3.py", line 30, in execute
    self.s3().Bucket(self.bucket).upload_file(self.filename, self.postgres())
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 239, in bucket_upload_file
    Config=Config,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
    callback=Callback,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 288, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 585, in _submit
    upload_input_manager.provide_transfer_size(transfer_future)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 244, in provide_transfer_size
    self._osutil.get_file_size(transfer_future.meta.call_args.fileobj)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/utils.py", line 247, in get_file_size
    return os.path.getsize(filename)
  File "/usr/local/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'golovanov'
[2022-11-22T01:15:15.962+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=PG_to_S3, task_id=PG_to_S3, execution_date=20221121T212612, start_date=20221122T011513, end_date=20221122T011515
[2022-11-22T01:15:15.974+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 184 for task PG_to_S3 ([Errno 2] No such file or directory: 'golovanov'; 28605)
[2022-11-22T01:15:16.035+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-22T01:15:16.055+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
