[2022-11-21T22:55:55.628+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: PG_to_S3.PG_to_S3 manual__2022-11-21T21:26:12.692587+00:00 [queued]>
[2022-11-21T22:55:55.637+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: PG_to_S3.PG_to_S3 manual__2022-11-21T21:26:12.692587+00:00 [queued]>
[2022-11-21T22:55:55.639+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-21T22:55:55.640+0000] {taskinstance.py:1363} INFO - Starting attempt 28 of 28
[2022-11-21T22:55:55.641+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-21T22:55:55.651+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresToS3Operator): PG_to_S3> on 2022-11-21 21:26:12.692587+00:00
[2022-11-21T22:55:55.659+0000] {standard_task_runner.py:55} INFO - Started process 21808 to run task
[2022-11-21T22:55:55.665+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'PG_to_S3', 'PG_to_S3', 'manual__2022-11-21T21:26:12.692587+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/PGtoS3.py', '--cfg-path', '/tmp/tmpkbn_v202']
[2022-11-21T22:55:55.669+0000] {standard_task_runner.py:83} INFO - Job 137: Subtask PG_to_S3
[2022-11-21T22:55:55.760+0000] {task_command.py:376} INFO - Running <TaskInstance: PG_to_S3.PG_to_S3 manual__2022-11-21T21:26:12.692587+00:00 [running]> on host b785e9657fa7
[2022-11-21T22:55:55.834+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=eugeny
AIRFLOW_CTX_DAG_ID=PG_to_S3
AIRFLOW_CTX_TASK_ID=PG_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T21:26:12.692587+00:00
AIRFLOW_CTX_TRY_NUMBER=28
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-21T21:26:12.692587+00:00
[2022-11-21T22:55:57.607+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/pgtos3.py", line 27, in execute
    self.s3().Bucket(self.bucket).upload_file(self.postgres(), Key=self.filename)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 239, in bucket_upload_file
    Config=Config,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
    callback=Callback,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 281, in upload_file
    raise ValueError('Filename must be a string')
ValueError: Filename must be a string
[2022-11-21T22:55:57.633+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=PG_to_S3, task_id=PG_to_S3, execution_date=20221121T212612, start_date=20221121T225555, end_date=20221121T225557
[2022-11-21T22:55:57.645+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 137 for task PG_to_S3 (Filename must be a string; 21808)
[2022-11-21T22:55:57.682+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-21T22:55:57.704+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
