[2022-11-21T22:54:35.425+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: PG_to_S3.PG_to_S3 manual__2022-11-21T21:26:12.692587+00:00 [queued]>
[2022-11-21T22:54:35.438+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: PG_to_S3.PG_to_S3 manual__2022-11-21T21:26:12.692587+00:00 [queued]>
[2022-11-21T22:54:35.439+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-21T22:54:35.441+0000] {taskinstance.py:1363} INFO - Starting attempt 27 of 27
[2022-11-21T22:54:35.442+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-21T22:54:35.454+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresToS3Operator): PG_to_S3> on 2022-11-21 21:26:12.692587+00:00
[2022-11-21T22:54:35.463+0000] {standard_task_runner.py:55} INFO - Started process 21745 to run task
[2022-11-21T22:54:35.469+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'PG_to_S3', 'PG_to_S3', 'manual__2022-11-21T21:26:12.692587+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/PGtoS3.py', '--cfg-path', '/tmp/tmpliw32ko4']
[2022-11-21T22:54:35.473+0000] {standard_task_runner.py:83} INFO - Job 136: Subtask PG_to_S3
[2022-11-21T22:54:35.551+0000] {task_command.py:376} INFO - Running <TaskInstance: PG_to_S3.PG_to_S3 manual__2022-11-21T21:26:12.692587+00:00 [running]> on host b785e9657fa7
[2022-11-21T22:54:35.615+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=eugeny
AIRFLOW_CTX_DAG_ID=PG_to_S3
AIRFLOW_CTX_TASK_ID=PG_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T21:26:12.692587+00:00
AIRFLOW_CTX_TRY_NUMBER=27
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-21T21:26:12.692587+00:00
[2022-11-21T22:54:37.282+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/pgtos3.py", line 27, in execute
    self.s3().Bucket(self.bucket).upload_file(self.postgres(), Key=self.filename)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 239, in bucket_upload_file
    Config=Config,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
    callback=Callback,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 281, in upload_file
    raise ValueError('Filename must be a string')
ValueError: Filename must be a string
[2022-11-21T22:54:37.302+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=PG_to_S3, task_id=PG_to_S3, execution_date=20221121T212612, start_date=20221121T225435, end_date=20221121T225437
[2022-11-21T22:54:37.313+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 136 for task PG_to_S3 (Filename must be a string; 21745)
[2022-11-21T22:54:37.382+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-21T22:54:37.407+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
