[2022-11-11T14:54:13.918+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.download manual__2022-11-11T14:54:10.947391+00:00 [queued]>
[2022-11-11T14:54:13.925+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.download manual__2022-11-11T14:54:10.947391+00:00 [queued]>
[2022-11-11T14:54:13.926+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-11T14:54:13.927+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-11T14:54:13.928+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-11T14:54:13.937+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): download> on 2022-11-11 14:54:10.947391+00:00
[2022-11-11T14:54:13.943+0000] {standard_task_runner.py:55} INFO - Started process 23723 to run task
[2022-11-11T14:54:13.947+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'download', 'manual__2022-11-11T14:54:10.947391+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/first_dug.py', '--cfg-path', '/tmp/tmpgrqu9ldq']
[2022-11-11T14:54:13.956+0000] {standard_task_runner.py:83} INFO - Job 82: Subtask download
[2022-11-11T14:54:14.011+0000] {task_command.py:376} INFO - Running <TaskInstance: first_dag.download manual__2022-11-11T14:54:10.947391+00:00 [running]> on host 0b03955da713
[2022-11-11T14:54:14.058+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=eugeny
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=download
AIRFLOW_CTX_EXECUTION_DATE=2022-11-11T14:54:10.947391+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-11T14:54:10.947391+00:00
[2022-11-11T14:54:14.802+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/first_dug.py", line 32, in load_data
    data = csv.reader(text, delimiter=',')
NameError: name 'text' is not defined
[2022-11-11T14:54:14.819+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=first_dag, task_id=download, execution_date=20221111T145410, start_date=20221111T145413, end_date=20221111T145414
[2022-11-11T14:54:14.829+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 82 for task download (name 'text' is not defined; 23723)
[2022-11-11T14:54:14.880+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-11T14:54:14.904+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
