[2022-11-10T20:12:51.215+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_third_dag.insert_table manual__2022-11-10T20:07:44.450017+00:00 [queued]>
[2022-11-10T20:12:51.223+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: a_third_dag.insert_table manual__2022-11-10T20:07:44.450017+00:00 [queued]>
[2022-11-10T20:12:51.224+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-10T20:12:51.225+0000] {taskinstance.py:1363} INFO - Starting attempt 4 of 4
[2022-11-10T20:12:51.226+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-10T20:12:51.236+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_table> on 2022-11-10 20:07:44.450017+00:00
[2022-11-10T20:12:51.243+0000] {standard_task_runner.py:55} INFO - Started process 16353 to run task
[2022-11-10T20:12:51.257+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'a_third_dag', 'insert_table', 'manual__2022-11-10T20:07:44.450017+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/third_dug.py', '--cfg-path', '/tmp/tmpzw6ngaw6']
[2022-11-10T20:12:51.259+0000] {standard_task_runner.py:83} INFO - Job 63: Subtask insert_table
[2022-11-10T20:12:51.361+0000] {task_command.py:376} INFO - Running <TaskInstance: a_third_dag.insert_table manual__2022-11-10T20:07:44.450017+00:00 [running]> on host 0b03955da713
[2022-11-10T20:12:51.426+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_third_dag
AIRFLOW_CTX_TASK_ID=insert_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-10T20:07:44.450017+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-10T20:07:44.450017+00:00
[2022-11-10T20:12:51.438+0000] {base.py:71} INFO - Using connection ID '***' for task execution.
[2022-11-10T20:12:51.445+0000] {sql.py:315} INFO - Running statement: 
             INSERT INTO currency_pair (date_scrapping, price, pair)
             VALUES (default, 1234, pair)
             ;
           , parameters: None
[2022-11-10T20:12:51.447+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "pair" does not exist
LINE 3:              VALUES (default, 1234, pair)
                                            ^
HINT:  There is a column named "pair" in table "currency_pair", but it cannot be referenced from this part of the query.

[2022-11-10T20:12:51.458+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=a_third_dag, task_id=insert_table, execution_date=20221110T200744, start_date=20221110T201251, end_date=20221110T201251
[2022-11-10T20:12:51.466+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 63 for task insert_table (column "pair" does not exist
LINE 3:              VALUES (default, 1234, pair)
                                            ^
HINT:  There is a column named "pair" in table "currency_pair", but it cannot be referenced from this part of the query.
; 16353)
[2022-11-10T20:12:51.510+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-10T20:12:51.528+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
